const Productos = [
    { id: 1, name: 'Bart Explode', desc: 'Extravagante y alocado cenicero hexagonal hecho a mano, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/BartExplode.png?raw=true', precio: '1200', stock: 4 },
    { id: 2, name: 'AlienCogo', desc: 'Un viajante del espacio vino a traernos paz, cenicero fabricado con resina, todo reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/AlienCogo.png?raw=true', precio: '1000', stock: 2 },
    { id: 3, name: 'BurbujaHigh', desc: 'Cenicero Burbuja super poderosa, hecho a mano, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/BurbujaHigh.png?raw=true', precio: '1200', stock: 41 },
    { id: 4, name: 'ChicasSP', desc: 'Las Chicas Superpoderosas, fabricado con resina reciclable', image: '', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/ChicasSP.png?raw=true', precio: '1000', stock: 2 },
    { id: 5, name: 'CogoAngel', desc: 'Extravagante y alocado cenicero, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/CogoAngel.png?raw=true', precio: '1200', stock: 4 },
    { id: 6, name: 'Excursio', desc: 'Todos los equipos de futbol, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/Excursio.png?raw=true', precio: '1200', stock: 15 },
    { id: 7, name: 'Mariposa', desc: 'Cenicero de mariposa, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/Mariposa.png?raw=true', precio: '1200', stock: 13 },
    { id: 8, name: 'MoneyBag', desc: 'Cenicero Bolsa de dinero, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/MoneyBag.png?raw=true', precio: '1200', stock: 7 },
    { id: 9, name: 'Vokita', desc: 'Ceni de Vokita, fabricado con resina reciclable', image: 'https://github.com/FacuP11/HydrusResin-PonceBritos/blob/master/src/components/images/Vokita.png?raw=true', precio: '1200', stock: 20 },

];